server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://110.8.21.243:25432/postgres
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
#      ddl-auto: validate # DB 에 DDL 무시
      ddl-auto: update  # DB 에 DDL 적용
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace